[parse]
net_name = "fastbev_part1_nuscenes"
framework = "onnx"
inputs = [ 6, 256, 704, 3]
inputs_layout = "NHWC"
inputs_dtype = "fp32"
pre_method = "nop"
pre_scale = [ 58.395, 57.12, 57.375 ]
pre_mean = [ 123.675, 116.28, 103.53 ]
channel_swap = [ 2, 1, 0 ]
network = "./fmodel/extractor/nuscenes/fastbev_part1_nuscenes.onnx"
jr_path = "../deploy/imodel/extractor/nuscenes"
target = "zhuge"
log_path = "./logs/extractor/nuscenes/parse"

[optimize]
target = "zhuge"
json = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_parsed.json"
raw = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_parsed.raw"
jr_path = "../deploy/imodel/extractor/nuscenes"
log_path = "./logs/extractor/nuscenes/optimize"

[quantize]
saturation = "kld"
forward_dir = "./qtset/extractor/nuscenes/coco"
forward_list = "./qtset/extractor/nuscenes/coco.txt"
json = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_optimized.json"
raw = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_optimized.raw"
jr_path = "../deploy/imodel/extractor/nuscenes"
per = "channel"
target = "zhuge"
qdtype = "int8"
log_path = "./logs/extractor/nuscenes/quantize"

[adapt]
target = "zhuge"
json = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_quantized.json"
raw = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_quantized.raw"
jr_path = "../deploy/imodel/extractor/nuscenes"
log_path = "./logs/extractor/nuscenes/adapt"

[generate]
json = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_adapted.json"
raw = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_adapted.raw"
jr_path = "../deploy/imodel/extractor/nuscenes"
log_path = "./logs/extractor/nuscenes/generate"

[run]
log_time = true
log_io = false
dump_format = "SFB"
json = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_ZG.json"
raw = "../deploy/imodel/extractor/nuscenes/fastbev_part1_nuscenes_ZG.raw"
input = "./test/part1_input.ftmp"
backends = "ZG330,socket://zg330aiu@192.168.125.166:9981?npu=0x40000000&dma=0x80000000;Host"
log_path = "./test/testlog"
dump_output = true
