[parse]
net_name = "fastbev_part3_vehicle_fp16"
framework = "onnx"
inputs = [ 1, 64, 200, 200, 4]
inputs_layout = "FD"
inputs_dtype = "fp32"
pre_method = "nop"
pre_scale = "nop"
pre_mean = "nop"
channel_swap = "nop"
pre_check = "false"
network = "./fmodel/decoder/vehicle/fastbev_part3_vehicle.onnx"
jr_path = "../deploy/imodel/decoder/vehicle_fp16"
target = "zhuge"
log_path = "./logs/decoder/vehicle_fp16/parse"

[optimize]
target = "zhuge"
json = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_parsed.json"
raw = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_parsed.raw"
jr_path = "../deploy/imodel/decoder/vehicle_fp16"
log_path = "./logs/decoder/vehicle_fp16/optimize"

[quantize]
saturation = "kld"
json = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_optimized.json"
raw = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_optimized.raw"
jr_path = "../deploy/imodel/decoder/vehicle_fp16"
per = "channel"
target = "zhuge"
qdtype = "fp16"
log_path = "./logs/decoder/vehicle_fp16/quantize"

[adapt]
target = "zhuge"
json = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_quantized.json"
raw = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_quantized.raw"
jr_path = "../deploy/imodel/decoder/vehicle_fp16"
log_path = "./logs/decoder/vehicle_fp16/adapt"

[generate]
json = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_adapted.json"
raw = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_adapted.raw"
jr_path = "../deploy/imodel/decoder/vehicle_fp16"
log_path = "./logs/decoder/vehicle_fp16/generate"

[run]
log_time = true
log_io = false
dump_format = "SFB"
backends = "ZG330,socket://zg330aiu@192.168.125.166:9981?npu=0x40000000&dma=0x80000000;Host"
json = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_ZG.json"
raw = "../deploy/imodel/decoder/vehicle_fp16/fastbev_part3_vehicle_fp16_ZG.raw"
input = "./test/part3_input.ftmp"
log_path = "./test/testlog/vehicle_fp16"
dump_output = true
