/*
 * tcp_icraft_runtime.cpp
 *
 * Board-side TCP1 runtime for the TCP CARLA model on Icraft XRT / ZG330.
 *
 * Data flow:
 *   PC TCP stream
 *     -> uint32_be packet_size + TCP1 packet
 *     -> tcp1_parse_frame()
 *     -> JPEG decode (libjpeg-turbo, RGB)
 *     -> ImageNet normalize, FP32 NHWC [1,256,900,3]
 *     -> state FP32 [1,9]
 *     -> Icraft Session::forward({rgb, state})
 *     -> pred_wp [1,4,2], mu_branches [1,2], sigma_branches [1,2]
 *     -> existing tcp_postprocess() (Beta + PID + fusion)
 *     -> TCP1 result -> PC
 *
 * This file is a self-contained board runtime: TCP1 protocol handling,
 * preprocessing, Icraft inference and control postprocessing are all here.
 *
 * Expected project-side dependencies:
 *   icraft_utils.hpp              (same helper used by the previous FastBEV runtime)
 *
 * TCP1 protocol parsing, CRC, ImageNet preprocessing and Beta/PID/fusion
 * postprocessing are intentionally embedded in this single source file.
 *   libturbojpeg
 *   Icraft XRT / ZG330Backend / HostBackend
 *
 * Model files:
 *   Use the JSON + RAW generated by Icraft.
 *
 * Example:
 * Default model paths:
 *   ./imodel/tcp/tcp_ZG.json
 *   ./imodel/tcp/tcp_ZG.raw
 *
 * Example:
 *   ./tcp_icraft_runtime \
 *       --device 'axi://zg330aiu?npu=0x40000000&dma=0x80000000' \
 *       --bind 0.0.0.0 \
 *       --port 5200
 */

#include <icraft-xrt/core/session.h>
#include <icraft-xrt/dev/host_device.h>
#include <icraft-xrt/dev/zg330_device.h>
#include <icraft-backends/zg330backend/zg330backend.h>
#include <icraft-backends/hostbackend/backend.h>
#include <icraft-backends/hostbackend/utils.h>

#include "icraft_utils.hpp"

#include <arpa/inet.h>
#include <errno.h>
#include <locale.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <turbojpeg.h>
#include <unistd.h>
#include <zlib.h>

#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <exception>
#include <stdexcept>
#include <string>
#include <vector>

using namespace icraft::xrt;
using namespace icraft::xir;

namespace {

using Clock = std::chrono::steady_clock;

constexpr int kImageWidth = 900;
constexpr int kImageHeight = 256;
constexpr int kImageChannels = 3;
constexpr size_t kRgbElements =
    static_cast<size_t>(kImageWidth) * kImageHeight * kImageChannels;
constexpr size_t kStateElements = 9;
constexpr size_t kPredWpElements = 8;
constexpr size_t kBranchElements = 2;

volatile sig_atomic_t g_stop = 0;


/* -------------------------------------------------------------------------- */
/* TCP1 protocol: merged from the original board/src/tcp1_protocol.c          */
/* -------------------------------------------------------------------------- */

constexpr char kTcp1Magic[5] = "TCP1";
constexpr uint16_t kTcp1Version = 1u;
constexpr uint16_t kTcp1MsgFrame = 1u;
constexpr uint16_t kTcp1MsgResult = 2u;
constexpr uint16_t kTcp1ImageEncodingJpeg = 1u;
constexpr uint16_t kTcp1ImageWidth = 900u;
constexpr uint16_t kTcp1ImageHeight = 256u;
constexpr uint16_t kTcp1ImageChannels = 3u;
constexpr uint32_t kTcp1StateCount = 9u;
constexpr size_t kTcp1MaxPacketBytes = 16u * 1024u * 1024u;
constexpr size_t kTcp1HeaderBytes = 32u;
constexpr size_t kTcp1FramePrefixBytes = 16u;
constexpr size_t kTcp1StateBytes = 36u;

struct tcp1_header_t {
    uint16_t message_type = 0;
    uint64_t frame_id = 0;
    uint64_t timestamp_ns = 0;
    uint32_t item_count = 0;
    uint32_t payload_size = 0;
};

struct tcp1_frame_t {
    tcp1_header_t header{};
    float state[kTcp1StateCount]{};
    const uint8_t* jpeg = nullptr;
    uint32_t jpeg_size = 0;
    uint32_t jpeg_crc32 = 0;
};

static uint16_t tcp1_read_be16(const uint8_t* p) {
    return static_cast<uint16_t>(
        (static_cast<uint16_t>(p[0]) << 8U) |
        static_cast<uint16_t>(p[1]));
}

static uint32_t tcp1_read_be32(const uint8_t* p) {
    return (static_cast<uint32_t>(p[0]) << 24U) |
           (static_cast<uint32_t>(p[1]) << 16U) |
           (static_cast<uint32_t>(p[2]) << 8U) |
           static_cast<uint32_t>(p[3]);
}

static uint64_t tcp1_read_be64(const uint8_t* p) {
    return (static_cast<uint64_t>(tcp1_read_be32(p)) << 32U) |
           static_cast<uint64_t>(tcp1_read_be32(p + 4));
}

static void tcp1_write_be16(uint8_t* p, uint16_t value) {
    p[0] = static_cast<uint8_t>(value >> 8U);
    p[1] = static_cast<uint8_t>(value);
}

static void tcp1_write_be32(uint8_t* p, uint32_t value) {
    p[0] = static_cast<uint8_t>(value >> 24U);
    p[1] = static_cast<uint8_t>(value >> 16U);
    p[2] = static_cast<uint8_t>(value >> 8U);
    p[3] = static_cast<uint8_t>(value);
}

static void tcp1_write_be64(uint8_t* p, uint64_t value) {
    tcp1_write_be32(p, static_cast<uint32_t>(value >> 32U));
    tcp1_write_be32(p + 4, static_cast<uint32_t>(value));
}

static int tcp1_recv_exact(int fd, void* buffer, size_t size) {
    auto* out = static_cast<uint8_t*>(buffer);
    size_t offset = 0;

    while (offset < size) {
        const ssize_t got = recv(fd, out + offset, size - offset, 0);
        if (got == 0) {
            return 1;
        }
        if (got < 0) {
            if (errno == EINTR) {
                continue;
            }
            return -1;
        }
        offset += static_cast<size_t>(got);
    }
    return 0;
}

static int tcp1_send_all(int fd, const void* buffer, size_t size) {
    const auto* data = static_cast<const uint8_t*>(buffer);
    size_t offset = 0;

    while (offset < size) {
        const ssize_t sent =
            send(fd, data + offset, size - offset, MSG_NOSIGNAL);
        if (sent < 0) {
            if (errno == EINTR) {
                continue;
            }
            return -1;
        }
        if (sent == 0) {
            return -1;
        }
        offset += static_cast<size_t>(sent);
    }
    return 0;
}

static int tcp1_recv_packet(
    int fd,
    uint8_t** buffer,
    size_t* capacity,
    size_t* packet_size
) {
    uint8_t length_bytes[4];
    if (buffer == nullptr || capacity == nullptr || packet_size == nullptr) {
        return -1;
    }

    int rc = tcp1_recv_exact(fd, length_bytes, sizeof(length_bytes));
    if (rc != 0) {
        return rc;
    }

    const uint32_t length = tcp1_read_be32(length_bytes);
    if (length < kTcp1HeaderBytes || length > kTcp1MaxPacketBytes) {
        std::fprintf(stderr, "[TCP1] invalid packet length: %u\n", length);
        return -1;
    }

    if (*capacity < static_cast<size_t>(length)) {
        auto* resized = static_cast<uint8_t*>(
            std::realloc(*buffer, static_cast<size_t>(length)));
        if (resized == nullptr) {
            return -1;
        }
        *buffer = resized;
        *capacity = static_cast<size_t>(length);
    }

    rc = tcp1_recv_exact(fd, *buffer, static_cast<size_t>(length));
    if (rc != 0) {
        return rc;
    }

    *packet_size = static_cast<size_t>(length);
    return 0;
}

static int tcp1_send_packet(
    int fd,
    const uint8_t* packet,
    size_t packet_size
) {
    if (packet == nullptr ||
        packet_size < kTcp1HeaderBytes ||
        packet_size > kTcp1MaxPacketBytes) {
        return -1;
    }

    uint8_t length_bytes[4];
    tcp1_write_be32(length_bytes, static_cast<uint32_t>(packet_size));

    if (tcp1_send_all(fd, length_bytes, sizeof(length_bytes)) != 0) {
        return -1;
    }
    return tcp1_send_all(fd, packet, packet_size);
}

static int tcp1_parse_header(
    const uint8_t* packet,
    size_t packet_size,
    tcp1_header_t* header
) {
    if (packet == nullptr ||
        header == nullptr ||
        packet_size < kTcp1HeaderBytes) {
        return -1;
    }

    if (std::memcmp(packet, kTcp1Magic, 4) != 0) {
        std::fprintf(stderr, "[TCP1] bad magic\n");
        return -1;
    }

    if (tcp1_read_be16(packet + 4) != kTcp1Version) {
        std::fprintf(stderr, "[TCP1] unsupported version\n");
        return -1;
    }

    header->message_type = tcp1_read_be16(packet + 6);
    header->frame_id = tcp1_read_be64(packet + 8);
    header->timestamp_ns = tcp1_read_be64(packet + 16);
    header->item_count = tcp1_read_be32(packet + 24);
    header->payload_size = tcp1_read_be32(packet + 28);

    if (static_cast<size_t>(header->payload_size) !=
        packet_size - kTcp1HeaderBytes) {
        std::fprintf(stderr, "[TCP1] payload length mismatch\n");
        return -1;
    }
    return 0;
}

static int tcp1_parse_frame(
    const uint8_t* packet,
    size_t packet_size,
    tcp1_frame_t* frame
) {
    if (frame == nullptr ||
        tcp1_parse_header(packet, packet_size, &frame->header) != 0) {
        return -1;
    }

    if (frame->header.message_type != kTcp1MsgFrame ||
        frame->header.item_count != 1u) {
        std::fprintf(stderr, "[TCP1] expected one-item frame\n");
        return -1;
    }

    if (frame->header.payload_size <
        kTcp1FramePrefixBytes + kTcp1StateBytes) {
        std::fprintf(stderr, "[TCP1] truncated frame payload\n");
        return -1;
    }

    const uint8_t* prefix = packet + kTcp1HeaderBytes;

    const uint16_t width = tcp1_read_be16(prefix);
    const uint16_t height = tcp1_read_be16(prefix + 2);
    const uint16_t channels = tcp1_read_be16(prefix + 4);
    const uint16_t encoding = tcp1_read_be16(prefix + 6);

    frame->jpeg_size = tcp1_read_be32(prefix + 8);
    frame->jpeg_crc32 = tcp1_read_be32(prefix + 12);

    if (width != kTcp1ImageWidth ||
        height != kTcp1ImageHeight ||
        channels != kTcp1ImageChannels ||
        encoding != kTcp1ImageEncodingJpeg) {
        std::fprintf(stderr, "[TCP1] image contract mismatch\n");
        return -1;
    }

    if (static_cast<size_t>(frame->jpeg_size) !=
        packet_size -
            kTcp1HeaderBytes -
            kTcp1FramePrefixBytes -
            kTcp1StateBytes) {
        std::fprintf(stderr, "[TCP1] JPEG length mismatch\n");
        return -1;
    }

    const uint8_t* state_bytes = prefix + kTcp1FramePrefixBytes;
    float command_sum = 0.0f;

    for (uint32_t i = 0; i < kTcp1StateCount; ++i) {
        const uint32_t bits = tcp1_read_be32(state_bytes + i * 4u);
        std::memcpy(&frame->state[i], &bits, sizeof(bits));

        if (!std::isfinite(frame->state[i])) {
            std::fprintf(stderr, "[TCP1] state contains NaN/Inf\n");
            return -1;
        }

        if (i >= 3u) {
            const float value = frame->state[i];
            if (!(std::fabs(value) < 1.0e-6f ||
                  std::fabs(value - 1.0f) < 1.0e-6f)) {
                std::fprintf(
                    stderr,
                    "[TCP1] command state is not one-hot\n");
                return -1;
            }
            command_sum += value;
        }
    }

    if (std::fabs(command_sum - 1.0f) >= 1.0e-6f) {
        std::fprintf(
            stderr,
            "[TCP1] command state must have one active entry\n");
        return -1;
    }

    frame->jpeg = state_bytes + kTcp1StateBytes;

    if (frame->jpeg_size < 4u ||
        frame->jpeg[0] != 0xffu ||
        frame->jpeg[1] != 0xd8u ||
        frame->jpeg[frame->jpeg_size - 2u] != 0xffu ||
        frame->jpeg[frame->jpeg_size - 1u] != 0xd9u) {
        std::fprintf(stderr, "[TCP1] invalid JPEG markers\n");
        return -1;
    }

    const uint32_t actual_crc = static_cast<uint32_t>(
        crc32(0L, frame->jpeg, frame->jpeg_size));

    if (actual_crc != frame->jpeg_crc32) {
        std::fprintf(stderr, "[TCP1] JPEG CRC mismatch\n");
        return -1;
    }

    return 0;
}

static int tcp1_pack_result(
    uint8_t* packet,
    size_t capacity,
    size_t* packet_size,
    uint64_t frame_id,
    uint64_t finished_ts_ns,
    float steer,
    float throttle,
    float brake,
    double jpeg_decode_ms,
    double preprocess_ms,
    double inference_ms,
    double postprocess_ms
) {
    if (packet == nullptr ||
        packet_size == nullptr ||
        capacity <= kTcp1HeaderBytes) {
        return -1;
    }

    char* json =
        reinterpret_cast<char*>(packet + kTcp1HeaderBytes);

    const int json_size = std::snprintf(
        json,
        capacity - kTcp1HeaderBytes,
        "{\"frame_id\":%llu,\"finished_ts_ns\":%llu,"
        "\"source\":\"tcp-board-icraft\","
        "\"control\":{\"steer\":%.9g,\"throttle\":%.9g,\"brake\":%.9g},"
        "\"timing_ms\":{\"jpeg_decode\":%.6f,\"preprocess\":%.6f,"
        "\"inference\":%.6f,\"postprocess\":%.6f}}",
        static_cast<unsigned long long>(frame_id),
        static_cast<unsigned long long>(finished_ts_ns),
        static_cast<double>(steer),
        static_cast<double>(throttle),
        static_cast<double>(brake),
        jpeg_decode_ms,
        preprocess_ms,
        inference_ms,
        postprocess_ms);

    if (json_size < 0 ||
        static_cast<size_t>(json_size) >=
            capacity - kTcp1HeaderBytes) {
        return -1;
    }

    const size_t total =
        kTcp1HeaderBytes + static_cast<size_t>(json_size);

    std::memcpy(packet, kTcp1Magic, 4);
    tcp1_write_be16(packet + 4, kTcp1Version);
    tcp1_write_be16(packet + 6, kTcp1MsgResult);
    tcp1_write_be64(packet + 8, frame_id);
    tcp1_write_be64(packet + 16, finished_ts_ns);
    tcp1_write_be32(packet + 24, 3u);
    tcp1_write_be32(
        packet + 28,
        static_cast<uint32_t>(json_size));

    *packet_size = total;
    return 0;
}

/* -------------------------------------------------------------------------- */
/* TCP model preprocess/postprocess: merged from board/src/tcp_pipeline.c     */
/* -------------------------------------------------------------------------- */

struct tcp_pid_t {
    float kp = 0.0f;
    float ki = 0.0f;
    float kd = 0.0f;
    float values[40]{};
    int next = 0;
    float sum = 0.0f;
};

struct tcp_postprocessor_t {
    tcp_pid_t turn{};
    tcp_pid_t speed{};
    float steer_history[20]{};
    int steer_count = 0;
    int steer_next = 0;
    int fusion_status = 0;
};

struct tcp_control_t {
    float steer = 0.0f;
    float throttle = 0.0f;
    float brake = 0.0f;
};

static float tcp_clipf(float value, float low, float high) {
    if (value < low) return low;
    if (value > high) return high;
    return value;
}

static void tcp_pid_init(
    tcp_pid_t* pid,
    float kp,
    float ki,
    float kd
) {
    std::memset(pid, 0, sizeof(*pid));
    pid->kp = kp;
    pid->ki = ki;
    pid->kd = kd;
}

static float tcp_pid_step(tcp_pid_t* pid, float error) {
    const int previous_index = (pid->next + 39) % 40;
    const float previous = pid->values[previous_index];
    const float oldest = pid->values[pid->next];

    pid->values[pid->next] = error;
    pid->next = (pid->next + 1) % 40;
    pid->sum += error - oldest;

    const float derivative = error - previous;

    return
        pid->kp * error +
        pid->ki * (pid->sum / 40.0f) +
        pid->kd * derivative;
}

static void tcp_postprocessor_init(tcp_postprocessor_t* post) {
    std::memset(post, 0, sizeof(*post));
    tcp_pid_init(&post->turn, 0.75f, 0.75f, 0.3f);
    tcp_pid_init(&post->speed, 5.0f, 0.5f, 1.0f);
}

static int tcp_preprocess_rgb_nhwc(
    const uint8_t* rgb_u8,
    int width,
    int height,
    float* rgb_float
) {
    static constexpr float mean[3] = {
        0.485f, 0.456f, 0.406f
    };
    static constexpr float stddev[3] = {
        0.229f, 0.224f, 0.225f
    };

    if (rgb_u8 == nullptr ||
        rgb_float == nullptr ||
        width != 900 ||
        height != 256) {
        return -1;
    }

    const size_t pixels =
        static_cast<size_t>(width) *
        static_cast<size_t>(height);

    for (size_t i = 0; i < pixels; ++i) {
        const size_t base = i * 3u;

        rgb_float[base] =
            (static_cast<float>(rgb_u8[base]) / 255.0f -
             mean[0]) / stddev[0];

        rgb_float[base + 1u] =
            (static_cast<float>(rgb_u8[base + 1u]) / 255.0f -
             mean[1]) / stddev[1];

        rgb_float[base + 2u] =
            (static_cast<float>(rgb_u8[base + 2u]) / 255.0f -
             mean[2]) / stddev[2];
    }

    return 0;
}

static float tcp_beta_value(
    float alpha,
    float beta,
    int action_index
) {
    float value = action_index == 1 ? 0.5f : 0.0f;

    if (alpha > 1.0f && beta > 1.0f) {
        value = (alpha - 1.0f) /
                (alpha + beta - 2.0f);
    } else if (alpha <= 1.0f && beta > 1.0f) {
        value = 0.0f;
    } else if (alpha > 1.0f && beta <= 1.0f) {
        value = 1.0f;
    } else {
        float denominator = alpha + beta;
        if (denominator < 1.0e-5f) {
            denominator = 1.0e-5f;
        }
        value = alpha / denominator;
    }

    return value * 2.0f - 1.0f;
}

static int tcp_postprocess(
    tcp_postprocessor_t* post,
    const float pred_wp[8],
    const float mu[2],
    const float sigma[2],
    const float state[9],
    tcp_control_t* control
) {
    if (post == nullptr ||
        pred_wp == nullptr ||
        mu == nullptr ||
        sigma == nullptr ||
        state == nullptr ||
        control == nullptr) {
        return -1;
    }

    float wp[8];
    float target[2];

    for (int i = 0; i < 8; ++i) {
        if (!std::isfinite(pred_wp[i])) {
            return -1;
        }
        wp[i] = pred_wp[i];
    }

    for (int i = 0; i < 2; ++i) {
        if (!std::isfinite(mu[i]) ||
            !std::isfinite(sigma[i])) {
            return -1;
        }
    }

    for (int i = 0; i < 9; ++i) {
        if (!std::isfinite(state[i])) {
            return -1;
        }
    }

    const float signed_acc =
        tcp_beta_value(mu[0], sigma[0], 0);

    const float ctrl_steer =
        tcp_clipf(
            tcp_beta_value(mu[1], sigma[1], 1),
            -1.0f,
            1.0f);

    float ctrl_throttle = 0.0f;
    float ctrl_brake = 0.0f;

    if (signed_acc >= 0.0f) {
        ctrl_throttle =
            tcp_clipf(signed_acc, 0.0f, 1.0f);
    } else {
        ctrl_brake =
            tcp_clipf(-signed_acc, 0.0f, 1.0f);
    }

    for (int i = 0; i < 4; ++i) {
        wp[i * 2 + 1] *= -1.0f;
    }

    target[0] = state[1];
    target[1] = -state[2];

    float desired_speed = 0.0f;
    float aim_x = wp[0];
    float aim_y = wp[1];
    float best_norm = 1.0e5f;

    for (int i = 0; i < 3; ++i) {
        const float dx =
            wp[(i + 1) * 2] - wp[i * 2];
        const float dy =
            wp[(i + 1) * 2 + 1] -
            wp[i * 2 + 1];

        const float midpoint_x =
            (wp[(i + 1) * 2] + wp[i * 2]) * 0.5f;
        const float midpoint_y =
            (wp[(i + 1) * 2 + 1] +
             wp[i * 2 + 1]) * 0.5f;

        const float midpoint_norm =
            std::hypot(midpoint_x, midpoint_y);

        desired_speed +=
            std::hypot(dx, dy) * (2.0f / 3.0f);

        if (std::fabs(4.0f - best_norm) >
            std::fabs(4.0f - midpoint_norm)) {
            aim_x = wp[i * 2];
            aim_y = wp[i * 2 + 1];
            best_norm = midpoint_norm;
        }
    }

    const float aim_last_x = wp[6] - wp[4];
    const float aim_last_y = wp[7] - wp[5];

    constexpr float kPi = 3.14159265358979323846f;

    const float angle =
        (0.5f * kPi - std::atan2(aim_y, aim_x)) *
        (2.0f / kPi);

    const float angle_last =
        (0.5f * kPi -
         std::atan2(aim_last_y, aim_last_x)) *
        (2.0f / kPi);

    const float angle_target =
        (0.5f * kPi -
         std::atan2(target[1], target[0])) *
        (2.0f / kPi);

    bool use_target =
        std::fabs(angle_target) < std::fabs(angle);

    if (std::fabs(angle_target - angle_last) > 0.3f &&
        target[1] < 10.0f) {
        use_target = true;
    }

    const float angle_final =
        use_target ? angle_target : angle;

    const float traj_steer =
        tcp_clipf(
            tcp_pid_step(&post->turn, angle_final),
            -1.0f,
            1.0f);

    const float speed = state[0] * 12.0f;

    const float ratio =
        desired_speed != 0.0f
            ? speed / desired_speed
            : INFINITY;

    float traj_brake =
        (desired_speed < 0.4f || ratio > 1.1f)
            ? 1.0f
            : 0.0f;

    const float delta =
        tcp_clipf(
            desired_speed - speed,
            0.0f,
            0.25f);

    float traj_throttle =
        tcp_clipf(
            tcp_pid_step(&post->speed, delta),
            0.0f,
            0.75f);

    if (traj_brake > 0.0f) {
        traj_throttle = 0.0f;
    }
    if (traj_brake < 0.05f) {
        traj_brake = 0.0f;
    }
    if (traj_throttle > traj_brake) {
        traj_brake = 0.0f;
    }

    constexpr float alpha = 0.3f;

    if (post->fusion_status == 0) {
        control->steer =
            alpha * ctrl_steer +
            (1.0f - alpha) * traj_steer;
        control->throttle =
            alpha * ctrl_throttle +
            (1.0f - alpha) * traj_throttle;
        control->brake =
            alpha * ctrl_brake +
            (1.0f - alpha) * traj_brake;
    } else {
        control->steer =
            alpha * traj_steer +
            (1.0f - alpha) * ctrl_steer;
        control->throttle =
            alpha * traj_throttle +
            (1.0f - alpha) * ctrl_throttle;
        control->brake =
            alpha * traj_brake +
            (1.0f - alpha) * ctrl_brake;
    }

    control->steer =
        tcp_clipf(control->steer, -1.0f, 1.0f);
    control->throttle =
        tcp_clipf(control->throttle, 0.0f, 0.75f);
    control->brake =
        tcp_clipf(control->brake, 0.0f, 1.0f);

    if (control->brake > 0.5f) {
        control->throttle = 0.0f;
    }

    post->steer_history[post->steer_next] =
        std::fabs(control->steer);

    post->steer_next =
        (post->steer_next + 1) % 20;

    if (post->steer_count < 20) {
        post->steer_count += 1;
    }

    int turning_count = 0;
    for (int i = 0; i < post->steer_count; ++i) {
        if (post->steer_history[i] > 0.10f) {
            turning_count += 1;
        }
    }

    post->fusion_status =
        turning_count > 10 ? 1 : 0;

    return 0;
}


struct Arguments {
    std::string json_path = "./imodel/tcp/tcp_ZG.json";
    std::string raw_path = "./imodel/tcp/tcp_ZG.raw";
    std::string device_url =
        "axi://zg330aiu?npu=0x40000000&dma=0x80000000";
    std::string bind_host = "0.0.0.0";
    int port = 5200;
};

void on_signal(int) {
    g_stop = 1;
}

uint64_t realtime_ns() {
    timespec ts{};
    clock_gettime(CLOCK_REALTIME, &ts);
    return static_cast<uint64_t>(ts.tv_sec) * 1000000000ull +
           static_cast<uint64_t>(ts.tv_nsec);
}

double monotonic_ms() {
    timespec ts{};
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return static_cast<double>(ts.tv_sec) * 1000.0 +
           static_cast<double>(ts.tv_nsec) / 1000000.0;
}

void usage(const char* program) {
    std::fprintf(
        stderr,
        "Usage: %s [--json MODEL.json] [--raw MODEL.raw] "
        "[--device URL] [--bind 0.0.0.0] [--port 5200]\n"
        "Defaults:\n"
        "  --json ./imodel/tcp/tcp_ZG.json\n"
        "  --raw  ./imodel/tcp/tcp_ZG.raw\n",
        program);
}

Arguments parse_arguments(int argc, char** argv) {
    Arguments args;

    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];

        if (arg == "--json" && i + 1 < argc) {
            args.json_path = argv[++i];
        } else if (arg == "--raw" && i + 1 < argc) {
            args.raw_path = argv[++i];
        } else if (arg == "--device" && i + 1 < argc) {
            args.device_url = argv[++i];
        } else if (arg == "--bind" && i + 1 < argc) {
            args.bind_host = argv[++i];
        } else if (arg == "--port" && i + 1 < argc) {
            args.port = std::stoi(argv[++i]);
        } else if (arg == "--help" || arg == "-h") {
            usage(argv[0]);
            std::exit(0);
        } else {
            throw std::runtime_error("unknown or incomplete argument: " + arg);
        }
    }

    if (args.device_url.empty()) {
        throw std::runtime_error("--device must not be empty");
    }
    if (args.bind_host.empty()) {
        throw std::runtime_error("--bind must not be empty");
    }
    if (args.port < 1 || args.port > 65535) {
        throw std::runtime_error("--port must be in 1..65535");
    }

    return args;
}

bool shape_is(const TensorType& type, std::initializer_list<int64_t> expected) {
    if (type->shape.size() != expected.size()) {
        return false;
    }

    size_t i = 0;
    for (int64_t dim : expected) {
        if (type->shape[i] != dim) {
            return false;
        }
        ++i;
    }
    return true;
}

void validate_model_contract(const Network& network) {
    const auto inputs = network.inputs();
    const auto outputs = network.outputs();

    if (inputs.size() != 2) {
        throw std::runtime_error(
            "model contract mismatch: expected exactly 2 inputs (rgb, state)");
    }

    /*
     * The deployment contract and parser command use this fixed order:
     *   input 0: rgb   FP32 NHWC [1,256,900,3]
     *   input 1: state FP32      [1,9]
     */
    if (!shape_is(inputs[0].tensorType(), {1, 256, 900, 3}) ||
        !inputs[0].tensorType()->element_dtype.isFP32()) {
        throw std::runtime_error(
            "model input[0] must be FP32 NHWC [1,256,900,3]");
    }

    if (!shape_is(inputs[1].tensorType(), {1, 9}) ||
        !inputs[1].tensorType()->element_dtype.isFP32()) {
        throw std::runtime_error(
            "model input[1] must be FP32 [1,9]");
    }

    if (outputs.size() != 3) {
        throw std::runtime_error(
            "model contract mismatch: expected exactly 3 outputs");
    }

    /*
     * Expected output order from the exported model:
     *   0 pred_wp        FP32 [1,4,2]
     *   1 mu_branches    FP32 [1,2]
     *   2 sigma_branches FP32 [1,2]
     */
    if (!shape_is(outputs[0].tensorType(), {1, 4, 2}) ||
        !outputs[0].tensorType()->element_dtype.isFP32()) {
        throw std::runtime_error(
            "model output[0] must be pred_wp FP32 [1,4,2]");
    }

    if (!shape_is(outputs[1].tensorType(), {1, 2}) ||
        !outputs[1].tensorType()->element_dtype.isFP32()) {
        throw std::runtime_error(
            "model output[1] must be mu_branches FP32 [1,2]");
    }

    if (!shape_is(outputs[2].tensorType(), {1, 2}) ||
        !outputs[2].tensorType()->element_dtype.isFP32()) {
        throw std::runtime_error(
            "model output[2] must be sigma_branches FP32 [1,2]");
    }
}

void configure_client_socket(int fd) {
    int one = 1;
    setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
    setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, &one, sizeof(one));

    timeval timeout{};
    timeout.tv_sec = 30;
    setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));
    setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &timeout, sizeof(timeout));
}

int create_listener(const std::string& bind_host, int port) {
    int server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) {
        throw std::runtime_error(
            std::string("socket failed: ") + std::strerror(errno));
    }

    int one = 1;
    setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));

    sockaddr_in address{};
    address.sin_family = AF_INET;
    address.sin_port = htons(static_cast<uint16_t>(port));

    if (inet_pton(AF_INET, bind_host.c_str(), &address.sin_addr) != 1) {
        close(server_fd);
        throw std::runtime_error("invalid --bind IPv4 address: " + bind_host);
    }

    if (bind(
            server_fd,
            reinterpret_cast<const sockaddr*>(&address),
            sizeof(address)) != 0) {
        const std::string message =
            std::string("bind failed: ") + std::strerror(errno);
        close(server_fd);
        throw std::runtime_error(message);
    }

    if (listen(server_fd, 2) != 0) {
        const std::string message =
            std::string("listen failed: ") + std::strerror(errno);
        close(server_fd);
        throw std::runtime_error(message);
    }

    return server_fd;
}

void copy_output_fp32(
    Tensor& device_tensor,
    size_t expected_elements,
    float* destination,
    const char* name
) {
    if (!device_tensor.waitForReady(std::chrono::seconds(20))) {
        throw std::runtime_error(
            std::string("Icraft output timeout: ") + name);
    }

    /*
     * The runtime tutorial requires moving the output from PLDDR to PS/host
     * memory before software post-processing.
     */
    Tensor host_tensor = device_tensor.to(HostDevice::MemRegion());

    if (!host_tensor.waitForReady(std::chrono::seconds(20))) {
        throw std::runtime_error(
            std::string("Icraft host-copy timeout: ") + name);
    }

    if (!host_tensor.dtype()->element_dtype.isFP32()) {
        throw std::runtime_error(
            std::string("Icraft output is not FP32: ") + name);
    }

    const uint64_t elements = host_tensor.dtype().numElements();
    if (elements != expected_elements) {
        throw std::runtime_error(
            std::string("Icraft output element count mismatch: ") + name);
    }

    host_tensor.read(
        reinterpret_cast<char*>(destination),
        0,
        expected_elements * sizeof(float));
}

void icraft_infer(
    Device& device,
    Session& session,
    const Value& rgb_input_value,
    const Value& state_input_value,
    float* rgb_nhwc,
    float* state,
    float* pred_wp,
    float* mu,
    float* sigma
) {
    bool need_reset = true;

    try {
        /*
         * data2Tensor() is the same project/modelzoo helper used by the
         * previous FastBEV runtime. It constructs an XRT Tensor using the
         * compiled network Value's dtype/shape/layout.
         *
         * IMPORTANT:
         *   rgb_nhwc is already normalized FP32 NHWC [1,256,900,3].
         *   Do not transpose it to NCHW here.
         */
        Tensor rgb_tensor =
            data2Tensor<float>(rgb_nhwc, rgb_input_value);
        Tensor state_tensor =
            data2Tensor<float>(state, state_input_value);

        std::vector<Tensor> outputs =
            session.forward({rgb_tensor, state_tensor});

        if (outputs.size() != 3) {
            throw std::runtime_error(
                "Icraft forward returned an unexpected number of outputs");
        }

        copy_output_fp32(
            outputs[0], kPredWpElements, pred_wp, "pred_wp");
        copy_output_fp32(
            outputs[1], kBranchElements, mu, "mu_branches");
        copy_output_fp32(
            outputs[2], kBranchElements, sigma, "sigma_branches");

        /*
         * Recommended by the Icraft runtime guide for continuous samples.
         * apply() is intentionally NOT called in the frame loop.
         */
        device.reset(1);
        need_reset = false;
    } catch (...) {
        /*
         * If a forward/copy fails, do a full reset once so that a following
         * client connection does not inherit a half-finished accelerator state.
         */
        if (need_reset) {
            try {
                device.reset(0);
            } catch (...) {
                // Preserve the original exception.
            }
        }
        throw;
    }
}

int serve_connection(
    int client_fd,
    Device& device,
    Session& session,
    const Value& rgb_input_value,
    const Value& state_input_value,
    tjhandle jpeg_decoder,
    uint8_t* rgb_u8,
    float* rgb_float
) {
    uint8_t* packet = nullptr;
    size_t packet_capacity = 0;
    size_t packet_size = 0;

    uint8_t result_packet[2048];
    size_t result_size = 0;

    tcp_postprocessor_t post{};
    tcp1_frame_t frame{};
    tcp_control_t control{};

    float pred_wp[kPredWpElements]{};
    float mu[kBranchElements]{};
    float sigma[kBranchElements]{};

    int rc = 0;

    /*
     * PID windows + steering/fusion history are route/connection scoped.
     * They are reset only when the PC creates a new TCP connection.
     */
    tcp_postprocessor_init(&post);

    while (!g_stop) {
        rc = tcp1_recv_packet(
            client_fd,
            &packet,
            &packet_capacity,
            &packet_size);

        if (rc != 0) {
            break;
        }

        if (tcp1_parse_frame(packet, packet_size, &frame) != 0) {
            std::fprintf(stderr, "[TCP1] invalid frame packet\n");
            rc = -1;
            break;
        }

        int width = 0;
        int height = 0;
        int subsamp = 0;
        int colorspace = 0;

        const double t0 = monotonic_ms();

        if (tjDecompressHeader3(
                jpeg_decoder,
                frame.jpeg,
                static_cast<unsigned long>(frame.jpeg_size),
                &width,
                &height,
                &subsamp,
                &colorspace) != 0) {
            std::fprintf(
                stderr,
                "[JPEG] header decode failed: %s\n",
                tjGetErrorStr2(jpeg_decoder));
            rc = -1;
            break;
        }

        if (width != kImageWidth || height != kImageHeight) {
            std::fprintf(
                stderr,
                "[JPEG] dimensions %dx%d do not match %dx%d\n",
                width,
                height,
                kImageWidth,
                kImageHeight);
            rc = -1;
            break;
        }

        if (tjDecompress2(
                jpeg_decoder,
                frame.jpeg,
                static_cast<unsigned long>(frame.jpeg_size),
                rgb_u8,
                width,
                width * kImageChannels,
                height,
                TJPF_RGB,
                TJFLAG_FASTDCT | TJFLAG_FASTUPSAMPLE) != 0) {
            std::fprintf(
                stderr,
                "[JPEG] decode failed: %s\n",
                tjGetErrorStr2(jpeg_decoder));
            rc = -1;
            break;
        }

        const double t1 = monotonic_ms();

        /*
         * JPEG decode produces RGB uint8 HWC [256,900,3].
         * Convert to normalized FP32 while preserving NHWC order.
         */
        if (tcp_preprocess_rgb_nhwc(
                rgb_u8, kImageWidth, kImageHeight, rgb_float) != 0) {
            std::fprintf(stderr, "[PRE] RGB preprocessing failed\n");
            rc = -1;
            break;
        }

        const double t2 = monotonic_ms();

        try {
            icraft_infer(
                device,
                session,
                rgb_input_value,
                state_input_value,
                rgb_float,
                frame.state,
                pred_wp,
                mu,
                sigma);
        } catch (const std::exception& error) {
            std::fprintf(
                stderr,
                "[ICRAFT] inference failed: %s\n",
                error.what());
            rc = -1;
            break;
        }

        const double t3 = monotonic_ms();

        if (tcp_postprocess(
                &post,
                pred_wp,
                mu,
                sigma,
                frame.state,
                &control) != 0) {
            std::fprintf(
                stderr,
                "[POST] non-finite tensor or invalid argument\n");
            rc = -1;
            break;
        }

        const double t4 = monotonic_ms();

        if (tcp1_pack_result(
                result_packet,
                sizeof(result_packet),
                &result_size,
                frame.header.frame_id,
                realtime_ns(),
                control.steer,
                control.throttle,
                control.brake,
                t1 - t0,
                t2 - t1,
                t3 - t2,
                t4 - t3) != 0) {
            std::fprintf(stderr, "[TCP1] failed to build result packet\n");
            rc = -1;
            break;
        }

        if (tcp1_send_packet(
                client_fd,
                result_packet,
                result_size) != 0) {
            std::fprintf(stderr, "[TCP1] failed to send result packet\n");
            rc = -1;
            break;
        }

        std::printf(
            "[FRAME] id=%llu jpeg=%uB control=(%+.3f,%.3f,%.3f) "
            "decode=%.2f pre=%.2f icraft=%.2f post=%.2f total=%.2f ms\n",
            static_cast<unsigned long long>(frame.header.frame_id),
            frame.jpeg_size,
            static_cast<double>(control.steer),
            static_cast<double>(control.throttle),
            static_cast<double>(control.brake),
            t1 - t0,
            t2 - t1,
            t3 - t2,
            t4 - t3,
            t4 - t0);
        std::fflush(stdout);
    }

    std::free(packet);
    return rc;
}

int run(const Arguments& args) {
    std::printf("============================================================\n");
    std::printf(" TCP CARLA Icraft ZG330 Runtime\n");
    std::printf("============================================================\n");
    std::printf("[Config] json=%s\n", args.json_path.c_str());
    std::printf("[Config] raw=%s\n", args.raw_path.c_str());
    std::printf("[Config] device=%s\n", args.device_url.c_str());
    std::printf("[Config] listen=%s:%d\n", args.bind_host.c_str(), args.port);

    /*
     * 1. Open board device.
     */
    Device device = Device::Open(args.device_url.c_str());
    bool device_open = true;

    int server_fd = -1;
    tjhandle jpeg_decoder = nullptr;
    uint8_t* rgb_u8 = nullptr;
    float* rgb_float = nullptr;

    try {
        /*
         * 2. Load Icraft JSON + RAW.
         */
        Network network = Network::CreateFromJsonFile(args.json_path);
        network.lazyLoadParamsFromFile(args.raw_path);

        validate_model_contract(network);

        const auto inputs = network.inputs();
        const Value rgb_input_value = inputs[0];
        const Value state_input_value = inputs[1];

        /*
         * 3. Build one ZG330 Session and deploy it once.
         *
         * Use the same modelzoo_utils initSession() path as the existing
         * FastBEV runtimes in this project. This avoids introducing a second
         * session-construction style and keeps backend setup consistent.
         *
         * Arguments after device:
         *   ocm_option   = -1    (SDK/default policy)
         *   mmu_mode     = true
         *   speed_mode   = false
         *   compress_ftmp= false
         */
        Session session = initSession(
            "zg330",
            network,
            device,
            -1,
            true,
            false,
            false);

        /*
         * apply() performs deployment/resource allocation. It is intentionally
         * called once here and never inside the frame loop.
         */
        session.apply();

        std::printf(
            "[Init] Icraft session applied; "
            "rgb=FP32 NHWC [1,256,900,3], state=FP32 [1,9]\n");

        /*
         * 4. JPEG decoder and reusable host buffers.
         */
        jpeg_decoder = tjInitDecompress();
        if (jpeg_decoder == nullptr) {
            throw std::runtime_error(
                "could not create libjpeg-turbo decoder");
        }

        rgb_u8 = static_cast<uint8_t*>(std::malloc(kRgbElements));
        rgb_float = static_cast<float*>(
            std::malloc(kRgbElements * sizeof(float)));

        if (rgb_u8 == nullptr || rgb_float == nullptr) {
            throw std::runtime_error(
                "failed to allocate RGB input buffers");
        }

        /*
         * 5. Start TCP service.
         */
        server_fd = create_listener(args.bind_host, args.port);

        std::printf(
            "[BOARD] listening on %s:%d\n",
            args.bind_host.c_str(),
            args.port);
        std::fflush(stdout);

        while (!g_stop) {
            sockaddr_in peer{};
            socklen_t peer_size = sizeof(peer);

            const int client_fd = accept(
                server_fd,
                reinterpret_cast<sockaddr*>(&peer),
                &peer_size);

            if (client_fd < 0) {
                if (errno == EINTR) {
                    continue;
                }
                throw std::runtime_error(
                    std::string("accept failed: ") +
                    std::strerror(errno));
            }

            configure_client_socket(client_fd);

            std::printf(
                "[BOARD] PC gateway connected: %s:%u\n",
                inet_ntoa(peer.sin_addr),
                static_cast<unsigned int>(ntohs(peer.sin_port)));
            std::fflush(stdout);

            /*
             * A connection owns the PID/fusion history. An inference/protocol
             * failure closes only this client; the board keeps listening.
             */
            serve_connection(
                client_fd,
                device,
                session,
                rgb_input_value,
                state_input_value,
                jpeg_decoder,
                rgb_u8,
                rgb_float);

            close(client_fd);

            std::printf("[BOARD] PC gateway disconnected\n");
            std::fflush(stdout);
        }

        if (server_fd >= 0) {
            close(server_fd);
            server_fd = -1;
        }

        std::free(rgb_u8);
        rgb_u8 = nullptr;

        std::free(rgb_float);
        rgb_float = nullptr;

        if (jpeg_decoder != nullptr) {
            tjDestroy(jpeg_decoder);
            jpeg_decoder = nullptr;
        }

        Device::Close(device);
        device_open = false;
        return 0;

    } catch (...) {
        if (server_fd >= 0) {
            close(server_fd);
        }

        std::free(rgb_u8);
        std::free(rgb_float);

        if (jpeg_decoder != nullptr) {
            tjDestroy(jpeg_decoder);
        }

        if (device_open) {
            try {
                Device::Close(device);
            } catch (...) {
                // Preserve the original exception.
            }
        }

        throw;
    }
}

}  // namespace

int main(int argc, char** argv) {
    setlocale(LC_NUMERIC, "C");

    struct sigaction action{};
    action.sa_handler = on_signal;
    sigemptyset(&action.sa_mask);
    sigaction(SIGINT, &action, nullptr);
    sigaction(SIGTERM, &action, nullptr);

    try {
        const Arguments args = parse_arguments(argc, argv);
        return run(args);
    } catch (const std::exception& error) {
        std::fprintf(stderr, "[Fatal] %s\n", error.what());
        return 1;
    }
}
